# -*- coding: utf-8 -*-
"""Homework1_Buse_Firat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KPTBLWr_h0UQLUabn81Y37zqu61ioCom
"""

import random as rnd
list2 = []

for i in range(3):
  list1 = []
  for j in range(3):
    x=rnd.randint(1,100)
    list1.append(x)
  list2.append(list1)

print (list2)

